= passage(1)

== Name

passage - password store utilizing age for encryption

== Synopsis

*passage* convert [*-v*] [_DIRECTORY_]

*passage* edit _FILE_...

*passage* generate [*-f*] [*-l* _LENGTH_] _FILE_

*passage* init

*passage* rm [*-rf*] [_FILE/DIRECTORY_...]

*passage* show [*-c*] [_FILE/DIRECTORY_...]

== Description

// TODO: age(1) doesn't actually exist, I should probably write one and contribute it upstream.

*passage* is a password store. It allows for storing passwords within a directory, by default
_${XDG_DATA_HOME}/share/passage_, encrypting them with age(1). It is based on the design of pass(1),
with deviation where pass(1) seems inconsistent or prone to feature-creep.

=== Goals

* Usage of age(1) rather than gpg(1). This helps to reduce the overall amount of cruft and bloat
  being used in cryptography programs, and while it's mostly a philosophical reason, it's the main
  reason this was written.
* POSIX sh(1) compatibility. pass(1) depends on bash(1), and uses quite a lot of bashisms, making
  using it with other default system shells require a lot of changes to the code. *passage* doesn't
  have any non-POSIX compatible requirements, aside from age(1).
* A preference of printing easily machine-readable content by default. pass(1)'s output tends to be
  geared more towards human-readability, which can occasionally be annoying for scripting and
  automated usage.
* Avoidance of piece-meal operations on password files. Most password editing operations, other
  than generating a new password, should just be done through a text editor.
* Conforming to XDG specifications by default. pass(1) does not, though it can be made to.

== Commands

When providing a password file as an argument, do not include the ".age" suffix.

*convert* [*-v*] [_DIRECTORY_]::
    Convert a pass(1) password store, _DIRECTORY_ to a passage(1) store.
    All files are decrypted using gpg(1), and then reencrypted with age(1).
    If *-v* is specified, the gpg(1)-encrypterd files will be listed to standard error
    as they are converted.
    If unspecified, _DIRECTORY_ is _PASSWORD_STORE_DIR_ (which is _~/.password-store_ by default).

*edit* _FILE_::
    Decrypt and open _FILE_ in your editor. The decrypted file is written to a temporary file with
    owner-only read and write permissions, and then written back to the original location.

*generate* [*-f*] [*-l* _LENGTH_] _FILE_::
    Generate a password of _LENGTH_ characters long to _FILE_. If a custom _LENGTH_ is unspecified,
    the default length is 24 characters long. The password contains alphabetical, numeric, and
    punctuation symbols. If the password file already exists, it will not overwrite it.
    If *-f* is specified, it will.

*init*::
    Create the password store directory. No arguments are taken, as the directory and keys (if not
    defaults) should be set in the config or environment (see _ENVIRONMENT_ and _FILES_) anyway.

*rm* [*-rf*] [_FILE/DIRECTORY_...]::
    Delete a file/directory in the password store. *-r* will remove a directory recursively, *-f*
    will not error out if the file or directory doesn't exist.

*show* [*-c*] [_FILE/DIRECTORY_...]::
    Show a list of password files and directories, or show the contents of a password file.
    Directories are listed with a trailing slash (_/_) at the end of a line, files do not.
    Files have their ".age" suffix removed for readability.
    If a path to a password file is given, the contents of that file are printed to standard output.
    If *-c* is specified and a password file is given, the contents are copied to your X clipboard
    using xsel(1), rather than being printed, and then the clipboard is cleared after 45 seconds.
    If you provide a path to a password directory, the directory is listed.
    If you provide no path of any sort, the entire password store is listed.

== Environment

_EDITOR_::
    The default editor used by the *edit* command. If not set, it defaults to vi(1).

_PASSAGE_DIR_::
    A directory containing the password store.
    If not specified, _${XDG_DATA_HOME}/passage_ is used instead.

_PASSAGE_KEY_::
    A file path. This is the key used for encrypting passwords; your private key.
    If not specified, _${XDG_CONFIG_HOME}/passage/privkey_ is used.

_PASSAGE_RECIPIENTS_::
    A file path. This is the list of public keys that password files are encrypted *for*; as in,
    this is what public keys should be able to decrypt password files.
    If not specified, _${XDG_CONFIG_HOME}/passage/recipients_ is used.

_PASSWORD_STORE_DIR_::
    If set, this directory is used by *convert*, rather than pass(1)'s own default,
    _~/.password-store_. It's not used if you provide directories as arguments to *convert*, though.
    This environment variable is also used by pass(1), thus the reason it is used here.

== Files

_${XDG_DATA_HOME}/passage_::
    The default location of the password store.
    The location can be changed with _PASSAGE_DIR_.
    By default, _XDG_DATA_HOME_ is set to *~/.local/share*.

_${XDG_CONFIG_HOME}/passage/passage.conf_::
    The default location of the configuration. Any variable mentioned in _ENVIRONMENT_ can be set
    here as well.
    By default _XDG_CONFIG_HOME_ is set to *~/.config*.

_${XDG_CONFIG_HOME}/passage/privkey_::
    The default location of the encrypting key, or private key.
    The encrypting key can be changed with _PASSAGE_KEY_.
    By default _XDG_CONFIG_HOME_ is set to *~/.config*.

_${XDG_CONFIG_HOME}/passage/recipients_::
    The default location of the recipients list.
    The location can be changed with _PASSAGE_RECIPIENTS_.
    By default _XDG_CONFIG_HOME_ is set to *~/.config*.

_${PASSAGE_DIR}/*.age_::
    Files encrypted with age(1).

== Notes

Since age(1) supports using SSH public/private key pairs for encrypting and decrypting, you can
actually just set _PASSAGE_KEY_ to *~/.ssh/id_rsa* (or similar) and _PASSAGE_RECIPIENTS_ to
*~/.ssh/id_rsa.pub* (again, or similar), and use your SSH keys for things.

== Bugs

There's an IRC channel for this and other utilities at <irc://irc.freenode.net/#mutiny>.
Please don't hesitate to message if you have questions.

== License

*passage* is in the public domain.

To the extent possible under law, Kylie McClain has waived all copyright and related or neighboring
rights to this work.

<http://creativecommons.org/publicdomain/zero/1.0/>
